### ISSUE TITLE
`ValidationSelfClient::validate_self_client()` should have an implementation

### ISSUE THREAD

**Issue by plafer** [informalsystems/basecoin-rs#116]
We should use the implementation [available in ibc-rs](https://github.com/cosmos/ibc-rs/blob/6d93e0c0f63b763dc92b6dac461d46139d3148b3/crates/ibc/src/hosts/tendermint/validate_self_client.rs#L21).

**Comment by Farhad-Shabani** [comment]
Have this: #75 😄
